/** Stable keys for engine / chrome UI strings (see builtin-ui + author `ui` in locales). */
export const UI = {
  langAuto:          'ui.langAuto',
  settingsLangLabel: 'ui.settingsLangLabel',
  settingsTitle:     'ui.settingsTitle',
  settingsClose:     'ui.settingsClose',
  settingsTheme:     'ui.settingsTheme',
  settingsThemeLight:  'ui.settingsThemeLight',
  settingsThemeDark:   'ui.settingsThemeDark',
  settingsThemeSystem: 'ui.settingsThemeSystem',
  settingsFont:      'ui.settingsFont',
  settingsAccent:    'ui.settingsAccent',
  settingsAccentDefault: 'ui.settingsAccentDefault',
  settingsAccentBlue:    'ui.settingsAccentBlue',
  settingsAccentOrange:  'ui.settingsAccentOrange',
  settingsAccentEmerald: 'ui.settingsAccentEmerald',
  settingsMusic:       'ui.settingsMusic',
  settingsMusicEnabled:  'ui.settingsMusicEnabled',
  settingsQuietMusicSr: 'ui.settingsQuietMusicSr',
  settingsSound:         'ui.settingsSound',
  settingsSoundEnabled:  'ui.settingsSoundEnabled',
  settingsVolumeLevel:  'ui.settingsVolumeLevel',
  settingsUnseenLabel: 'ui.settingsUnseenLabel',
  settingsResetSeen:   'ui.settingsResetSeen',
  settingsResetAll:    'ui.settingsResetAll',
  settingsExport:      'ui.settingsExport',
  settingsImport:      'ui.settingsImport',

  savesTitle:          'ui.savesTitle',
  savesClose:          'ui.savesClose',
  savesAuto:           'ui.savesAuto',
  savesNoData:         'ui.savesNoData',
  savesEmpty:          'ui.savesEmpty',
  savesLoad:           'ui.savesLoad',
  savesSave:           'ui.savesSave',
  savesDelete:         'ui.savesDelete',
  savesConfirmDelete:  'ui.savesConfirmDelete',
  savesConfirmOverwrite: 'ui.savesConfirmOverwrite',
  savesYes:            'ui.savesYes',
  savesNo:             'ui.savesNo',

  toolbarUndo:       'ui.toolbarUndo',
  toolbarRedo:       'ui.toolbarRedo',
  toolbarSaves:      'ui.toolbarSaves',
  toolbarSettings:   'ui.toolbarSettings',

  sessionMenuBrand:    'ui.sessionMenuBrand',
  sessionNewGame:      'ui.sessionNewGame',
  sessionLoadGame:     'ui.sessionLoadGame',
} as const

export type UiKey = (typeof UI)[keyof typeof UI]
